---
title: "23_24 cleaning"
author: "Caroline Nguyen"
date: "2026-03-16"
output: pdf_document
---

# _Initial set-up_

## _Loading in packages and setting working directory_

```{r, setup, include = FALSE}

knitr::opts_knit$set(root.dir='C:/Users/cangu/Documents/recess minutes 2025/SB291-Recess-Data')

library(tidyverse)

```

## _Loading 23-24 data_

```{r}

data <- read_csv("raw data/23-24_data.csv")
cds <- read_csv("raw data/23_24_double entry.csv")

```

## _Cleaning_

```{r}

#dropping the check column
data <- data[-1]

# fixing cdscode
cds <- cds %>% select(cdscode, district, school)
merge <- left_join(data,
                   cds,
                   by = c("district", "school"),
                   multiple = "any",
                   suffix = c("_x","_y"))
merge <- merge %>% select(-cdscode_x)
merge <- rename(merge, cdscode = cdscode_y)

# reorder columns
merge <- merge %>% select(cdscode, everything())
length(unique(merge$cdscode)) #2991 schools
unique(merge$schedule) # 4 types of schedules including NA 

```

## _Bringing in free reduced price meal data_

```{r}

frpm <- read_csv("raw data/frpm2324.csv")

# Creating cdscode variable 
frpm <- unite(frpm,
              col = cdscode,
              `County Code`:`School Code`,
              sep = "")
frpm$cdscode <- as.numeric(frpm$cdscode)

# Merging frpm data with recess data
merge2 <- left_join(merge,
                    frpm,
                    by = "cdscode")

# keeping only elementary schools
list(unique(merge2$`School Type`))
merge2 <- merge2 %>% filter(`School Type` != "Intermediate/Middle Schools (Public)")

```

## _Bringing in demographic data_

```{r}

demo <- read_csv("processed data/demo_2324_clean.csv")
merge3 <- left_join(merge2,
                    demo,
                    by = "cdscode")
data_2324 <- merge3
rm(cds, data, demo, frpm, merge, merge2, merge3)

data_2324 <- data_2324  %>% select(-c(`Academic Year`:IRC)) %>% select(-c(`CALPADS Fall 1 \nCertification Status`:`school.y`))

```

## _Reordering and renaming columns_

```{r}

data_2324[,"year"] <- 0

colnames(data_2324)

data_2324 <- rename(data_2324, "district"= "district.x")
data_2324 <- rename(data_2324, "school"= "school.x")
data_2324 <- rename(data_2324, "fourrec2" = "fourre2")

data_2324 <- data_2324[,c("cdscode","schedule","district","school","year","days1","days2","days3","days4","days5","sum","tkd",
                          "kd","first","second","third","fourth","fifth","sixth","tkrec1","krec1","onerec1","tworec1","threerec1",
                          "fourrec1","fiverec1","sixrec1", "tklunch","klunch","onelunch","twolunch",
                          "threelunch","fourlunch","fivelunch","sixlunch",
                          "tkrec2","krec2","onerec2","tworec2","threerec2","fourrec2","fiverec2",
                          "sixrec2","Low Grade","High Grade","Enrollment \n(K-12)","Free Meal \nCount \n(K-12)",
                          "Percent (%) \nEligible Free \n(K-12)","FRPM Count \n(K-12)","Percent (%) \nEligible FRPM \n(K-12)",
                          "Enrollment \n(Ages 5-17)","Free Meal \nCount \n(Ages 5-17)","Percent (%) \nEligible Free \n(Ages 5-17)",
                          "FRPM Count \n(Ages 5-17)","Percent (%) \nEligible FRPM \n(Ages 5-17)","afriameri","native",
                          "asian","filipino","hispanic","notreport","pacisland","multiracial","white","male","female","nonbinary",
                          "miss_gen","ell","disability","socioeco","migrant","foster","homeless")]

length((unique(data_2324$cdscode))) #2959 schools left

```

## _Exporting as csv_

```{r}

write.csv(data_2324,"processed data/data_23-24.csv", row.names=FALSE)

```