---
title: "reshaping demographic data"
author: "Caroline Nguyen"
date: "2026-03-17"
output: pdf_document
---
# _Initial set-up_

## _Loading in packages and setting working directory_

```{r, setup, include = FALSE}

knitr::opts_knit$set(root.dir='C:/Users/cangu/Documents/recess minutes 2025/SB291-Recess-Data')

library(tidyverse)

```

## _Loading demographic data_

```{r}

demo <- read_csv("raw data/cenroll2324.csv")
colnames(demo) <- tolower(colnames(demo))

```

# _Cleaning_

```{r}

# Keeping only school level data
demo <- demo %>% filter(aggregatelevel == "S")

# Creating cdscode variable
demo <- unite(demo,
              col = cdscode,
              countycode:schoolcode,
              sep = "")
demo$cdscode <- as.numeric(demo$cdscode)

# Keeping only necessary variables
demo <- demo %>% select(cdscode:schoolname, reportingcategory, cumulativeenrollment)

# Turning enrollment into numeric 
demo$cumulativeenrollment[demo$cumulativeenrollment %in% "*"] <- ""
demo$cumulativeenrollment <- as.numeric(demo$cumulativeenrollment)

```

# _Race data_

```{r}

race <- demo %>% filter(grepl("R",reportingcategory))
race <- race %>% mutate(race = 1)
race$race[race$reportingcategory %in% "RI"] <- 2
race$race[race$reportingcategory %in% "RA"] <- 3
race$race[race$reportingcategory %in% "RF"] <- 4
race$race[race$reportingcategory %in% "RH"] <- 5
race$race[race$reportingcategory %in% "RD"] <- 6
race$race[race$reportingcategory %in% "RP"] <- 7
race$race[race$reportingcategory %in% "RT"] <- 8
race$race[race$reportingcategory %in% "RW"] <- 9

race <- race %>% select(-reportingcategory)

reshape(race, direction = "wide", 
        idvar = c("cdscode", "countyname", "districtname", "schoolname"),
        timevar = "race")

```

# _Gender data_

```{r}

```

# _Other data_

```{r}

```

